const baseCodeToProp = {
  KeyA: 'keyA',
  KeyB: 'keyB',
  KeyC: 'keyC',
  KeyD: 'keyD',
  KeyE: 'keyE',
  KeyF: 'keyF',
  KeyG: 'keyG',
  KeyH: 'keyH',
  KeyI: 'keyI',
  KeyJ: 'keyJ',
  KeyK: 'keyK',
  KeyL: 'keyL',
  KeyM: 'keyM',
  KeyN: 'keyN',
  KeyO: 'keyO',
  KeyP: 'keyP',
  KeyQ: 'keyQ',
  KeyR: 'keyR',
  KeyS: 'keyS',
  KeyT: 'keyT',
  KeyU: 'keyU',
  KeyV: 'keyV',
  KeyW: 'keyW',
  KeyX: 'keyX',
  KeyY: 'keyY',
  KeyZ: 'keyZ',
  Digit0: 'digit0',
  Digit1: 'digit1',
  Digit2: 'digit2',
  Digit3: 'digit3',
  Digit4: 'digit4',
  Digit5: 'digit5',
  Digit6: 'digit6',
  Digit7: 'digit7',
  Digit8: 'digit8',
  Digit9: 'digit9',
  Minus: 'minus',
  Equal: 'equal',
  BracketLeft: 'bracketLeft',
  BracketRight: 'bracketRight',
  Backslash: 'backslash',
  Semicolon: 'semicolon',
  Quote: 'quote',
  Backquote: 'backquote',
  Comma: 'comma',
  Period: 'period',
  Slash: 'slash',
  ArrowUp: 'arrowUp',
  ArrowDown: 'arrowDown',
  ArrowLeft: 'arrowLeft',
  ArrowRight: 'arrowRight',
  Home: 'home',
  End: 'end',
  PageUp: 'pageUp',
  PageDown: 'pageDown',
  Tab: 'tab',
  CapsLock: 'capsLock',
  ShiftLeft: 'shiftLeft',
  ShiftRight: 'shiftRight',
  ControlLeft: 'controlLeft',
  ControlRight: 'controlRight',
  AltLeft: 'altLeft',
  AltRight: 'altRight',
  Enter: 'enter',
  Space: 'space',
  Backspace: 'backspace',
  Delete: 'delete',
  Escape: 'escape',
  MouseLeft: 'mouseLeft',
  MouseRight: 'mouseRight',
  MetaLeft: 'metaLeft',
}

const basePropToLabel = {
  keyA: 'A',
  keyB: 'B',
  keyC: 'C',
  keyD: 'D',
  keyE: 'E',
  keyF: 'F',
  keyG: 'G',
  keyH: 'H',
  keyI: 'I',
  keyJ: 'J',
  keyK: 'K',
  keyL: 'L',
  keyM: 'M',
  keyN: 'N',
  keyO: 'O',
  keyP: 'P',
  keyQ: 'Q',
  keyR: 'R',
  keyS: 'S',
  keyT: 'T',
  keyU: 'U',
  keyV: 'V',
  keyW: 'W',
  keyX: 'X',
  keyY: 'Y',
  keyZ: 'Z',
  digit0: '0',
  digit1: '1',
  digit2: '2',
  digit3: '3',
  digit4: '4',
  digit5: '5',
  digit6: '6',
  digit7: '7',
  digit8: '8',
  digit9: '9',
  minus: '-',
  equal: '=',
  bracketLeft: '[',
  bracketRight: ']',
  backslash: '\\',
  semicolon: ';',
  quote: '"',
  backquote: '`',
  comma: ',',
  period: '.',
  slash: '/',
  arrowUp: 'Up',
  arrowDown: 'Down',
  arrowLeft: 'Left',
  arrowRight: 'Right',
  home: 'Home',
  end: 'End',
  pageUp: 'PageUp',
  pageDown: 'PageDown',
  tab: 'Tab',
  capsLock: 'CapsLock',
  shiftLeft: 'Shift',
  shiftRight: 'Shift',
  controlLeft: 'Ctrl',
  controlRight: 'Ctrl',
  altLeft: 'Alt',
  altRight: 'Alt',
  enter: 'Enter',
  space: 'Space',
  backspace: 'Backspace',
  delete: 'Delete',
  escape: 'Esc',
  mouseLeft: 'LMB',
  mouseRight: 'RMB',
  metaLeft: 'Cmd',
}

function generateInverse(mapping) {
  const inverse = {}
  for (const [key, value] of Object.entries(mapping)) {
    inverse[value] = key
  }
  return inverse
}

export const codeToProp = baseCodeToProp
export const propToCode = generateInverse(baseCodeToProp)
export const propToLabel = basePropToLabel
