const CONTROL_PRIORITY_SYSTEM = 0
const CONTROL_PRIORITY_USER = 100
const CONTROL_PRIORITY_XR = 50

export const ControlPriorities = { CONTROL_PRIORITY_SYSTEM, CONTROL_PRIORITY_USER, CONTROL_PRIORITY_XR }
