export const ErrorCodes = {
  SYSTEM: {
    INITIALIZATION_FAILED: 'SYSTEM_INIT_FAILED',
    DESTROYED: 'SYSTEM_DESTROYED',
    SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
    INVALID_CONFIG: 'INVALID_CONFIG'
  },

  NETWORK: {
    CONNECTION_FAILED: 'NET_CONNECT_FAILED',
    DISCONNECTED: 'NET_DISCONNECTED',
    TIMEOUT: 'NET_TIMEOUT',
    INVALID_MESSAGE: 'NET_INVALID_MESSAGE',
    MESSAGE_TOO_LARGE: 'NET_MSG_TOO_LARGE',
    DECODE_FAILED: 'NET_DECODE_FAILED'
  },

  ENTITY: {
    NOT_FOUND: 'ENTITY_NOT_FOUND',
    INVALID_TYPE: 'ENTITY_INVALID_TYPE',
    SPAWN_FAILED: 'ENTITY_SPAWN_FAILED',
    DESTROY_FAILED: 'ENTITY_DESTROY_FAILED'
  },

  ASSET: {
    NOT_FOUND: 'ASSET_NOT_FOUND',
    LOAD_FAILED: 'ASSET_LOAD_FAILED',
    INVALID_FORMAT: 'ASSET_INVALID_FORMAT',
    CORRUPTED: 'ASSET_CORRUPTED'
  },

  BLUEPRINT: {
    NOT_FOUND: 'BLUEPRINT_NOT_FOUND',
    INVALID: 'BLUEPRINT_INVALID',
    LOAD_FAILED: 'BLUEPRINT_LOAD_FAILED',
    PARSE_FAILED: 'BLUEPRINT_PARSE_FAILED'
  },

  SCRIPT: {
    EXECUTION_FAILED: 'SCRIPT_EXECUTION_FAILED',
    PARSE_ERROR: 'SCRIPT_PARSE_ERROR',
    RUNTIME_ERROR: 'SCRIPT_RUNTIME_ERROR',
    TIMEOUT: 'SCRIPT_TIMEOUT'
  },

  PHYSICS: {
    SIMULATION_FAILED: 'PHYSICS_SIM_FAILED',
    INVALID_SHAPE: 'PHYSICS_INVALID_SHAPE',
    CONSTRAINT_FAILED: 'PHYSICS_CONSTRAINT_FAILED'
  },

  DATABASE: {
    CONNECTION_FAILED: 'DB_CONNECT_FAILED',
    QUERY_FAILED: 'DB_QUERY_FAILED',
    CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',
    NOT_FOUND: 'DB_NOT_FOUND'
  },

  VALIDATION: {
    INVALID_INPUT: 'VALIDATION_INVALID_INPUT',
    MISSING_REQUIRED: 'VALIDATION_MISSING_REQUIRED',
    TYPE_MISMATCH: 'VALIDATION_TYPE_MISMATCH',
    OUT_OF_RANGE: 'VALIDATION_OUT_OF_RANGE'
  },

  PERMISSION: {
    DENIED: 'PERMISSION_DENIED',
    UNAUTHORIZED: 'PERMISSION_UNAUTHORIZED',
    INSUFFICIENT_RANK: 'PERMISSION_INSUFFICIENT_RANK'
  },

  CONFIGURATION: {
    MISSING: 'CONFIG_MISSING',
    INVALID: 'CONFIG_INVALID',
    TYPE_MISMATCH: 'CONFIG_TYPE_MISMATCH'
  },

  RESOURCE: {
    EXHAUSTED: 'RESOURCE_EXHAUSTED',
    NOT_AVAILABLE: 'RESOURCE_NOT_AVAILABLE',
    ALLOCATION_FAILED: 'RESOURCE_ALLOCATION_FAILED'
  },

  INTEGRATION: {
    EXTERNAL_SERVICE_FAILED: 'INTEGRATION_SERVICE_FAILED',
    API_ERROR: 'INTEGRATION_API_ERROR',
    TIMEOUT: 'INTEGRATION_TIMEOUT'
  }
}

export function getErrorCategory(code) {
  for (const [category, codes] of Object.entries(ErrorCodes)) {
    if (Object.values(codes).includes(code)) {
      return category
    }
  }
  return 'UNKNOWN'
}

export function isErrorCode(value) {
  for (const codes of Object.values(ErrorCodes)) {
    if (Object.values(codes).includes(value)) {
      return true
    }
  }
  return false
}
