export const RESOLUTION = 2
export const WIDTH = 200 * RESOLUTION
export const HEIGHT = 35 * RESOLUTION
export const GRID_COLS = 5
export const GRID_ROWS = 20
export const MAX_INSTANCES = GRID_COLS * GRID_ROWS
export const BORDER_RADIUS = 10 * RESOLUTION
export const NAME_FONT_SIZE = 16 * RESOLUTION
export const NAME_OUTLINE_SIZE = 4 * RESOLUTION
export const HEALTH_MAX = 100
export const HEALTH_HEIGHT = 12 * RESOLUTION
export const HEALTH_WIDTH = 100 * RESOLUTION
export const HEALTH_BORDER = 1.5 * RESOLUTION
export const HEALTH_BORDER_RADIUS = 20 * RESOLUTION
