const env = typeof process !== 'undefined' && process.env ? process.env : {}
const getFloat = (key, def) => parseFloat(env[key] ?? def)
const getInt = (key, def) => parseInt(env[key] ?? def, 10)

export const PhysicsConfig = {
  CAPSULE_RADIUS: getFloat('PHYSICS_CAPSULE_RADIUS', 0.3),
  CAPSULE_HEIGHT: getFloat('PHYSICS_CAPSULE_HEIGHT', 1.8),
  MASS: getFloat('PHYSICS_MASS', 70),
  GRAVITY: getFloat('PHYSICS_GRAVITY', 9.81),
  GROUND_DRAG: getFloat('PHYSICS_GROUND_DRAG', 0.8),
  AIR_DRAG: getFloat('PHYSICS_AIR_DRAG', 0.1),
  JUMP_HEIGHT: getFloat('PHYSICS_JUMP_HEIGHT', 1.5),
  JUMP_IMPULSE: getFloat('PHYSICS_JUMP_IMPULSE', 7.0),
  MAX_AIR_JUMPS: getInt('PHYSICS_MAX_AIR_JUMPS', 1),
  WALK_SPEED: getFloat('PHYSICS_WALK_SPEED', 4.0),
  RUN_SPEED: getFloat('PHYSICS_RUN_SPEED', 7.0),
  FLY_SPEED: getFloat('PHYSICS_FLY_SPEED', 10.0),
  FLY_DRAG: getFloat('PHYSICS_FLY_DRAG', 0.95),
  FLY_FORCE_MULTIPLIER: getFloat('PHYSICS_FLY_FORCE', 3.0),
  GROUND_DETECTION_RADIUS: getFloat('PHYSICS_GROUND_RADIUS', 0.35),
  GROUND_SLOPE_MAX: getFloat('PHYSICS_GROUND_SLOPE', 0.5),
  GROUND_SLOPE_THRESHOLD: getFloat('PHYSICS_GROUND_THRESHOLD', 0.3),
  GROUND_SWEEP_OFFSET: getFloat('PHYSICS_GROUND_SWEEP_OFFSET', 0.12),
  GROUND_SWEEP_DISTANCE: getFloat('PHYSICS_GROUND_SWEEP_DISTANCE', 0.1),
  PLATFORM_RAYCAST_DISTANCE: getFloat('PHYSICS_PLATFORM_RAYCAST', 2),
  PLATFORM_RAYCAST_OFFSET: getFloat('PHYSICS_PLATFORM_OFFSET', 0.2),
  PUSH_FORCE_DECAY: getFloat('PHYSICS_PUSH_DECAY', 0.95),
  PUSH_DRAG: getFloat('PHYSICS_PUSH_DRAG', 20),
  FALL_DAMAGE_THRESHOLD: getFloat('PHYSICS_FALL_THRESHOLD', 1.6),
  FALL_TIMER_THRESHOLD: getFloat('PHYSICS_FALL_TIMER', 0.1),
  FALL_VELOCITY: getFloat('PHYSICS_FALL_VELOCITY', -5),
  GRAVITY_PLATFORM_FACTOR: getFloat('PHYSICS_GRAVITY_PLATFORM', 0.2),
  SLIPPING_GRAVITY: getFloat('PHYSICS_SLIPPING_GRAVITY', 0.5),
  DRAG_COEFFICIENT: getFloat('PHYSICS_DRAG_COEFF', 10),
}

export const RenderingConfig = {
  SHADOW_MAP_SIZE: getInt('RENDER_SHADOW_SIZE', 2048),
  SHADOW_BIAS: getFloat('RENDER_SHADOW_BIAS', 0.0001),
  SHADOW_NORMAL_BIAS: getFloat('RENDER_SHADOW_NORMAL_BIAS', 0.02),
  CSM_SPLITS: getInt('RENDER_CSM_SPLITS', 4),
  CSM_LAMBDA: getFloat('RENDER_CSM_LAMBDA', 0.5),
  FOG_START: getFloat('RENDER_FOG_START', 10),
  FOG_END: getFloat('RENDER_FOG_END', 1000),
  FOG_DISTANCE_OFFSET: getFloat('RENDER_FOG_OFFSET', 5),
  ANTIALIASING: env.RENDER_AA !== 'false',
  ANISOTROPIC_FILTERING: getInt('RENDER_ANISO', 8),
  PIXEL_RATIO: getFloat('RENDER_PIXEL_RATIO', 1),
}

export const NetworkConfig = {
  SERVER_TICK_RATE: getInt('NET_TICK_RATE', 60),
  PLAYER_UPDATE_RATE: getFloat('NET_UPDATE_RATE', 8),
  SNAPSHOT_INTERVAL: getFloat('NET_SNAPSHOT_INTERVAL', 1),
  PING_TIMEOUT: getInt('NET_PING_TIMEOUT', 5000),
  CONNECTION_TIMEOUT: getInt('NET_CONN_TIMEOUT', 10000),
  DISCONNECTION_TIMEOUT: getInt('NET_DISC_TIMEOUT', 30000),
  SAVE_INTERVAL: getInt('SAVE_INTERVAL', 60),
  MAX_UPLOAD_SIZE: getInt('PUBLIC_MAX_UPLOAD_SIZE', 50 * 1024 * 1024),
  UPLOAD_TIMEOUT: getInt('NET_UPLOAD_TIMEOUT', 60000),
  ENABLE_COMPRESSION: env.NET_COMPRESSION !== 'false',
  MAX_MESSAGE_SIZE: getInt('NET_MAX_MSG_SIZE', 1024 * 100),
}

export const InputConfig = {
  POINTER_SENSITIVITY: getFloat('INPUT_POINTER_SENS', 1),
  POINTER_LOOK_SPEED: getFloat('INPUT_POINTER_SPEED', 0.001),
  POINTER_INVERT_Y: env.INPUT_INVERT_Y === 'true',
  PAN_LOOK_SPEED: getFloat('INPUT_PAN_SPEED', 0.002),
  TOUCH_DEADZONE: getFloat('INPUT_DEADZONE', 0.2),
  TOUCH_FULL_EXTENT: getFloat('INPUT_FULL_EXTENT', 0.8),
  ZOOM_SPEED: getFloat('INPUT_ZOOM_SPEED', 0.02),
  ZOOM_MIN: getFloat('INPUT_ZOOM_MIN', 0.1),
  ZOOM_MAX: getFloat('INPUT_ZOOM_MAX', 3),
  FIRST_PERSON_THRESHOLD: getFloat('INPUT_FP_THRESHOLD', 0.9),
  DEFAULT_ZOOM: getFloat('INPUT_DEFAULT_ZOOM', 1.5),
  STICK_DEAD_ZONE: getFloat('INPUT_STICK_DEADZONE', 0.2),
  KEY_REPEAT_DELAY: getInt('INPUT_REPEAT_DELAY', 500),
  KEY_REPEAT_INTERVAL: getInt('INPUT_REPEAT_INTERVAL', 30),
}

export const AvatarConfig = {
  VRM_DEFAULT_SCALE: getFloat('AVATAR_SCALE', 1),
  VRM_BLEND_SHAPE_WEIGHT: getFloat('AVATAR_BLEND_WEIGHT', 1),
  ANIMATION_FADE_DURATION: getFloat('ANIM_FADE', 0.2),
  LOCOMOTION_WALK_SPEED: getFloat('ANIM_WALK', 0.5),
  LOCOMOTION_RUN_SPEED: getFloat('ANIM_RUN', 1.0),
  EMOTE_DURATION: getFloat('EMOTE_DURATION', 3),
  NAMETAG_OFFSET: getFloat('NAMETAG_OFFSET', 2),
  DEFAULT_HEIGHT: getFloat('AVATAR_DEFAULT_HEIGHT', 1.6),
  HEAD_HEIGHT_OFFSET: getFloat('AVATAR_HEAD_OFFSET', 0.2),
  CAM_HEIGHT_FACTOR: getFloat('AVATAR_CAM_HEIGHT_FACTOR', 0.9),
}

export const ChatConfig = {
  MAX_MESSAGES: getInt('CHAT_MAX_MESSAGES', 50),
  MESSAGE_TIMEOUT: getInt('CHAT_TIMEOUT', 300000),
  BUBBLE_DISPLAY_TIME: getFloat('CHAT_BUBBLE_TIME', 5),
  BUBBLE_OFFSET_Y: getFloat('CHAT_BUBBLE_OFFSET', 2),
  MESSAGE_COOLDOWN: getInt('CHAT_COOLDOWN', 100),
  MAX_MESSAGES_PER_MINUTE: getInt('CHAT_RATE_LIMIT', 60),
}

export const AudioConfig = {
  MASTER_VOLUME: getFloat('AUDIO_MASTER', 1.0),
  EFFECTS_VOLUME: getFloat('AUDIO_EFFECTS', 0.8),
  VOICE_VOLUME: getFloat('AUDIO_VOICE', 1.0),
  MAX_SPATIAL_DISTANCE: getFloat('AUDIO_MAX_DISTANCE', 100),
  VOICE_CODEC: env.AUDIO_CODEC ?? 'opus',
}

export const PerformanceConfig = {
  TARGET_FPS: getInt('PERF_TARGET_FPS', 60),
  MIN_FRAME_TIME: 1000 / getInt('PERF_TARGET_FPS', 60),
  MAX_DELTA_TIME: getFloat('PERF_MAX_DELTA', 1 / 30),
  FIXED_DELTA_TIME: getFloat('PERF_FIXED_DELTA', 1 / 50),
  QUALITY_LEVEL: getInt('PERF_QUALITY', 2),
  MAX_CACHED_ASSETS: getInt('PERF_MAX_CACHE', 100),
  ASSET_CLEANUP_INTERVAL: getInt('PERF_CLEANUP', 60000),
}

export const ErrorConfig = {
  CAPTURE_ERRORS: env.CAPTURE_ERRORS !== 'false',
  MAX_ERROR_HISTORY: getInt('ERROR_MAX_HISTORY', 500),
  ERROR_CLEANUP_INTERVAL: getInt('ERROR_CLEANUP', 3600000),
  DEBUG_MODE: env.DEBUG === 'true',
  VERBOSE_LOGGING: env.VERBOSE === 'true',
  LOG_NETWORK_MESSAGES: env.LOG_NETWORK === 'true',
}

export const BuilderConfig = {
  SNAP_DEGREES: 5,
  SNAP_DISTANCE: 1,
  PROJECT_MAX: 500,
  TRANSFORM_LIMIT: parseInt(env.BUILDER_TRANSFORM_LIMIT ?? 50, 10),
}

export const NametagConfig = {
  RESOLUTION: parseInt(env.NAMETAG_RESOLUTION ?? 2, 10),
  GRID_COLS: parseInt(env.NAMETAG_GRID_COLS ?? 5, 10),
  GRID_ROWS: parseInt(env.NAMETAG_GRID_ROWS ?? 20, 10),
  WIDTH: parseInt(env.NAMETAG_WIDTH ?? 200, 10),
  HEIGHT: parseInt(env.NAMETAG_HEIGHT ?? 35, 10),
}

export const RenderConfig = {
  ACTION_BATCH_SIZE: parseInt(env.RENDER_ACTION_BATCH ?? 500, 10),
  LOD_BATCH_SIZE: parseInt(env.RENDER_LOD_BATCH ?? 1000, 10),
}

export const WorldConfig = {
  MAX_DELTA_TIME: parseFloat(env.WORLD_MAX_DELTA ?? 1 / 30),
  FIXED_DELTA_TIME: parseFloat(env.WORLD_FIXED_DELTA ?? 1 / 50),
}
