export const EVENT = {
  player: 'player',
  name: 'name',
  health: 'health',
  rank: 'rank',
  speaking: 'speaking',
  playerJoined: 'playerJoined',
  playerMuted: 'playerMuted',
  entity: {
    added: 'entityAdded',
    removed: 'entityRemoved',
    created: 'entityCreated',
  },
  action: {
    changed: 'actionChanged',
    onStart: 'action.onStart:',
    onTrigger: 'action.onTrigger:',
    onCancel: 'action.onCancel:',
  },
  input: {
    pointerDown: 'pointerdown',
    pointerUp: 'pointerup',
    pointerMove: 'pointermove',
    pointerCancel: 'pointercancel',
    keyDown: 'keydown',
    keyUp: 'keyup',
    wheel: 'wheel',
    drag: 'drag',
    dragEnter: 'dragenter',
    dragLeave: 'dragleave',
    dragOver: 'dragover',
    drop: 'drop',
    click: 'click',
    contextMenu: 'contextmenu',
    touchStart: 'touchstart',
    focus: 'focus',
    blur: 'blur',
  },
  physics: {
    contact: 'onContact',
    shapeHit: 'onShapeHit',
    controllerHit: 'onControllerHit',
    obstacleHit: 'onObstacleHit',
    constraintBreak: 'onConstraintBreak',
    constraintRelease: 'onConstraintRelease',
    sleep: 'onSleep',
    wake: 'onWake',
    trigger: 'onTrigger',
    originShift: 'onOriginShift',
    comShift: 'onComShift',
  },
  connection: {
    connect: 'connect',
    connected: 'connected',
    disconnect: 'disconnect',
    disconnected: 'disconnected',
    connectionFailed: 'connectionFailed',
  },
  livekit: 'livekitStatusChanged',
  ui: {
    toast: 'toast',
    confirm: 'confirm',
    avatar: 'avatar',
    actions: 'actions',
    chat: 'chat',
    close: 'close',
  },
  game: {
    enter: 'enter',
    leave: 'leave',
    buildModeChanged: 'buildModeChanged',
    stick: 'stick',
    command: 'command',
    dynamic: 'dynamic',
  },
  error: {
    critical: 'criticalError',
    captured: 'errorCaptured',
    uncaught: 'uncaughtException',
    unhandledRejection: 'unhandledRejection',
  },
  network: {
    ready: 'ready',
    start: 'start',
    end: 'end',
    message: 'message',
    event: 'event',
    sending: 'sending',
    sent: 'sent',
    pong: 'pong',
  },
  settings: {
    pref: 'prefChanged',
    setting: 'settingChanged',
    xrSession: 'xrSession',
  },
  lifecycle: {
    update: 'update',
    fixedUpdate: 'fixedUpdate',
    lateUpdate: 'lateUpdate',
    destroy: 'destroy',
    error: 'error',
    handled: 'handled',
    exit: 'exit',
    cleared: 'cleared',
  },
  pointer: {
    lock: 'pointerLockChanged',
    lockChange: 'pointerlockchange',
  },
  other: {
    emitting: 'emitting',
    progress: 'progress',
    graphicsResize: 'graphicsResize',
    resize: 'resize',
    visibilityChange: 'visibilitychange',
    blueprint: 'blueprintModified',
    admin: 'admin',
    kinematic: 'kinematic',
    pinned: 'Pinned',
    unpinned: 'Un-pinned',
    unlinked: 'Unlinked',
    kick: 'kick',
  },
}
