// Variable name mapping and material compatibility matrix for CustomShaderMaterial

export const variableMap = {
  diffuse: 'csm_DiffuseColor',
  roughness: 'csm_Roughness',
  metalness: 'csm_Metalness',
  emissive: 'csm_Emissive',
  ao: 'csm_AO',
  bump: 'csm_Bump',
  fragNormal: 'csm_FragNormal',
  clearcoat: 'csm_Clearcoat',
  clearcoatRoughness: 'csm_ClearcoatRoughness',
  clearcoatNormal: 'csm_ClearcoatNormal',
  transmission: 'csm_Transmission',
  thickness: 'csm_Thickness',
  iridescence: 'csm_Iridescence',
  pointSize: 'csm_PointSize',
  fragColor: 'csm_FragColor',
  depthAlpha: 'csm_DepthAlpha',
  unlitFac: 'csm_UnlitFac',
  position: 'csm_Position',
  positionRaw: 'csm_PositionRaw',
  normal: 'csm_Normal',
}

export const materialCompatibility = {
  [`${variableMap.position}`]: '*',
  [`${variableMap.positionRaw}`]: '*',
  [`${variableMap.normal}`]: '*',
  [`${variableMap.depthAlpha}`]: '*',
  [`${variableMap.pointSize}`]: ['PointsMaterial'],
  [`${variableMap.diffuse}`]: '*',
  [`${variableMap.fragColor}`]: '*',
  [`${variableMap.fragNormal}`]: '*',
  [`${variableMap.unlitFac}`]: '*',
  [`${variableMap.emissive}`]: ['MeshStandardMaterial', 'MeshPhysicalMaterial'],
  [`${variableMap.roughness}`]: ['MeshStandardMaterial', 'MeshPhysicalMaterial'],
  [`${variableMap.metalness}`]: ['MeshStandardMaterial', 'MeshPhysicalMaterial'],
  [`${variableMap.iridescence}`]: ['MeshStandardMaterial', 'MeshPhysicalMaterial'],
  [`${variableMap.ao}`]: [
    'MeshStandardMaterial',
    'MeshPhysicalMaterial',
    'MeshBasicMaterial',
    'MeshLambertMaterial',
    'MeshPhongMaterial',
    'MeshToonMaterial',
  ],
  [`${variableMap.bump}`]: [
    'MeshLambertMaterial',
    'MeshMatcapMaterial',
    'MeshNormalMaterial',
    'MeshPhongMaterial',
    'MeshPhysicalMaterial',
    'MeshStandardMaterial',
    'MeshToonMaterial',
    'ShadowMaterial',
  ],
  [`${variableMap.clearcoat}`]: ['MeshPhysicalMaterial'],
  [`${variableMap.clearcoatRoughness}`]: ['MeshPhysicalMaterial'],
  [`${variableMap.clearcoatNormal}`]: ['MeshPhysicalMaterial'],
  [`${variableMap.transmission}`]: ['MeshPhysicalMaterial'],
  [`${variableMap.thickness}`]: ['MeshPhysicalMaterial'],
}

export const featureDependencies = {
  clearcoat: [variableMap.clearcoat, variableMap.clearcoatNormal, variableMap.clearcoatRoughness],
  transmission: [variableMap.transmission],
  iridescence: [variableMap.iridescence],
}
