export function setupDebugMonitoring(world) {
  return {
    getFeatures: () => world.features || {},
    getCapabilities: () => world.capabilities || {},
    getDegradationStatus: () => ({
      audio: world.audio?.degraded || false,
      livekit: world.livekit?.degraded || false,
      network: world.network?.offlineMode || false,
      features: world.features || {},
      capabilities: world.capabilities || {},
    }),
    getFallbackLog: () => world.loader?.getFallbackLog?.() || [],

    performance: {
      getStats: (label) => world.performanceMonitor?.getStats(label) || null,
      getAllStats: () => world.performanceMonitor?.getAllStats() || {},
      getViolations: (limit) => world.performanceMonitor?.getViolations(limit) || [],
      getViolationSummary: () => world.performanceMonitor?.getViolationSummary() || [],
      getBudget: (category, path) => world.performanceBudget?.getBudget(category, path) || null,
      getBudgets: () => world.performanceBudget?.BUDGETS || {},
      isEnabled: () => world.performanceMonitor?.enabled || false,
      enable: () => world.performanceMonitor?.enable(),
      disable: () => world.performanceMonitor?.disable(),
      setSampleRate: (rate) => world.performanceMonitor?.setSampleRate(rate),
      clear: () => world.performanceMonitor?.clear(),
      getSampleData: () => ({
        framePhases: world.performanceMonitor?.samples.framePhases.getAll() || [],
        systemPhases: world.performanceMonitor?.samples.systemPhases.getAll() || [],
        entityOperations: world.performanceMonitor?.samples.entityOperations.getAll() || [],
      }),
    },

    memory: {
      takeSnapshot: (label) => world.memoryAnalyzer?.takeSnapshot(label)?.export(),
      getSnapshot: (index) => world.memoryAnalyzer?.getSnapshot(index)?.export() || null,
      getAllSnapshots: () => world.memoryAnalyzer?.getAllSnapshots().map(s => s.export()) || [],
      compareSnapshots: (index1, index2) => world.memoryAnalyzer?.compareSnapshots(index1, index2) || null,
      getLeaks: () => world.memoryAnalyzer?.detectLeaks() || [],
      getReport: () => world.memoryAnalyzer?.getReport() || null,
      getGrowthRate: (startIndex, endIndex) => world.memoryAnalyzer?.getGrowthRate(startIndex, endIndex) || null,
      getHeapTrend: () => world.memoryAnalyzer?.getHeapTrend() || [],
      getObjectTypeTrend: (type) => world.memoryAnalyzer?.getObjectTypeGrowthTrend(type) || [],
      clear: () => world.memoryAnalyzer?.clear(),
      getMetadata: () => {
        const snapshots = world.memoryAnalyzer?.getAllSnapshots() || []
        return {
          snapshotCount: snapshots.length,
          totalCapacity: world.memoryAnalyzer?.maxSnapshots || 0,
          timespan: snapshots.length > 1 ? {
            start: snapshots[0].timestamp,
            end: snapshots[snapshots.length - 1].timestamp,
            duration: snapshots[snapshots.length - 1].timestamp - snapshots[0].timestamp,
          } : null,
        }
      },
    },

    degradation: {
      registerFeature: (name, options) => world.degradation?.registerFeature(name, options),
      enableFeature: (name, testFn) => world.degradation?.enableFeature(name, testFn),
      getFeatureStatus: (name) => world.degradation?.getFeatureStatus(name),
      getAllStatus: () => world.degradation?.getAllStatus(),
      getDegradationStatus: () => world.degradation?.getDegradationStatus(),
      isFeatureAvailable: (name) => world.degradation?.isFeatureAvailable(name),
      isFeatureDegraded: (name) => world.degradation?.isFeatureDegraded(name),
      canContinue: (name) => world.degradation?.canContinue(name),
      getReport: () => world.degradation?.getReport(),
      activateFallback: (name) => world.degradation?.activateFallback(name),
    },

    dashboard: {
      getDashboard: () => world.dashboard?.getDashboard(),
      getMetric: (name) => world.dashboard?.getMetric(name),
      getAllMetrics: () => world.dashboard?.getAllMetrics(),
      getMetricHistory: (name, limit) => world.dashboard?.getMetricHistory(name, limit),
      getMetricStats: (name) => world.dashboard?.getMetricStats(name),
      getActiveAlerts: () => world.dashboard?.getActiveAlerts(),
      acknowledgeAlert: (alertId) => world.dashboard?.acknowledgeAlert(alertId),
      clearAlerts: () => world.dashboard?.clearAlerts(),
      getSummary: () => world.dashboard?.getSummary(),
      getTrends: () => world.dashboard?.getTrends(),
      getTopMetrics: (limit) => world.dashboard?.getTopMetrics(limit),
      startCollection: () => world.metricsCollector?.setupDefaultCollectors().setupThresholds().start(),
      stopCollection: () => world.metricsCollector?.stop(),
      getHealthReport: () => world.metricsCollector?.getHealthReport(),
      getMetricsByCategory: () => world.metricsCollector?.getMetricsByCategory(),
      setThreshold: (metric, value, severity) => world.dashboard?.setThreshold(metric, value, severity),
    },

    events: {
      getEmitterStats: (name) => world.eventAudit?.getEmitterStats(name),
      getAllStats: () => world.eventAudit?.getAllStats(),
      getEventHistory: (emitter, event, limit) => world.eventAudit?.getEventHistory(emitter, event, limit),
      getTopEvents: (limit) => world.eventAudit?.getTopEvents(limit),
      getAnomalies: (threshold) => world.eventAudit?.getAnomalies(threshold),
      getAuditReport: () => world.eventAudit?.getReport(),
      enableAudit: () => world.eventAudit?.enable(),
      disableAudit: () => world.eventAudit?.disable(),
      clearAudit: () => world.eventAudit?.clear(),
      registerEvent: (name, options) => world.eventRegistry?.registerEvent(name, options),
      getEvent: (name) => world.eventRegistry?.getEvent(name),
      getEventsByCategory: (category) => world.eventRegistry?.getEventsByCategory(category),
      getAllEvents: () => world.eventRegistry?.getAllEvents(),
      getDocumentation: (name) => world.eventRegistry?.getEventDocumentation(name),
      getAllDocumentation: () => world.eventRegistry?.getAllDocumentation(),
      validateEventData: (name, data) => world.eventRegistry?.validateEventData(name, data),
      exportRegistry: () => world.eventRegistry?.exportRegistry(),
    },
  }
}
